const mongoose = require('mongoose');

const activitySchema = new mongoose.Schema({
     Name: String,
     ID: String,
     Gender: String,
     DOB: Date,
     Age: Number,
     Class: String,
     DominantSide: String,
     ParentName: String,
     ParentMobileNo: String,
     AlternateNo: String,
     EmailID: String,
     ResidenceArea: String,
     ResidenceCity: String,
     SchoolName: String,
     SchoolID: String,
     SchoolContactName: String,
     SchoolContactNumber: String,
     SchoolContactEmailID: String,
     AssessmentTeam: String,
     AssessmentDate: String,
     AssessmentID: String,
     HeightCMs: Number,
     HeightRating: Number,
     WeightKG: Number,
     WeightRating: Number,
     BMI: Number,
     BmiRating: Number,
     BodyFatPercentage: Number,
     BodyFatRating: Number,
     ArmLengthCMs: Number,
     ArmLengthRating: Number,
     LegLengthCMs: Number,
     LegLengthRating: Number,
     SitAndReachCMs: Number,
     SitAndReachRating: Number,
     SingleLegBalance: Number,
     SingleLegBalanceRating: Number,
     PushUps: Number,
     PushUpsRating: Number,
     GripStrengthKGs: Number,
     GripStrengthRating: Number,
     SquatTest30Secs: Number,
     SquatTestRating: Number,
     PlankSecs: Number,
     PlankRating: Number,
     StandingLongJumpCMs: Number,
     StandingLongJumpRating: Number,
     StandingVerticalJumpInches: Number,
     StandingVerticalJumpRating: Number,
     FiveZeroFiveSecs: Number,
     FiveZeroFiveRating: Number,
     Speed30MtrsSecs: Number,
     Speed30MtrsRating: Number,
     SixHundredMtrsMins: Number,
     SixHundredMtrsRating: Number,
     OneMileTest: Number,
     OneMileTestRating: Number,
     BearPositionHoldRating: Number,
     OverheadSquatsRating: Number,
     LungesRating: Number,
     RemarksRemark1: String,
     RemarksRemark2: String,
     RemarksRemark3: String,

}, {
     timestamps: true
});

const Activity = mongoose.model('Activity', activitySchema);

export default Activity;